### ISSUE TITLE
Work on the ranking algorithm 

### ISSUE THREAD

**Issue by danielvdao** [danielvdao/karma_farm_backend#2]
Use a tree to store the initial comment as the root, and store replies as children. We need to score it somehow also.

**Comment by danielvdao** [comment]
The algorithm works as following - 
- For an optimal comment, it's high up in the tree because of its score and has no children.

**Comment by samtipton** [comment]
I have a skeleton for the algorithm on branch algo. 
It is not tested and the formula i used is pretty basic now. 

rank = 1000 - (karma score/ total karma in view \* scale_factor) - (# replies \* scale_factor) - (depth \* scale_factor)

I would be cool if we get have the formula bounded by the possible color values we will use on the app so the rank is directly translated to an RGB value.
